lang: de

author:
  - Lukas Arnold
  - Simone Arnold
  - Florian Bagemihl
  - Matthias Baitsch
  - Marc Fehr
  - Franca Hollmann
  - Maik Poetzsch
  - Sebastian Seipel
date: today

execute: 
  echo: true

toc-depth: 1
number-depth: 1
number-sections: true

format: 
  revealjs:
    overview: true
    slide-number: "c/t"
    code-line-numbers: false
    footer: "Bausteine Computergestützter Datenanalyse"
    theme: 
      - bcd-style-slides.scss
      - bcd-style-titlepage.scss
    resources:
      - _brand

citation:
  type: document
  title: "Bausteine Computergestützter Datenanalyse: Werkzeugbausteine R"
  url: https://github.com/bausteine-der-datenanalyse/bcd-bausteine-r
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Franca Hollmann
    - Maik Poetzsch
    - Sebastian Seipel
  issued: 2025

license: CC BY-SA

project:
  output-dir: __output
