project: 
  output-dir: _output
  render:
    - "*.qmd"
    - "!aufgaben.qmd"

execute: 
  echo: true

lang: de
toc-depth: 1
number-depth: 1
number-sections: true

format: 
  revealjs:
    overview: true
    slide-number: "c/t"
    code-line-numbers: false
    theme: 
    - bcd-style-slides.scss