project: 
  output-dir: _output

execute: 
  echo: true

lang: de

format: 
  revealjs:
    overview: true
    slide-number: "c/t"
    code-line-numbers: false
    number-sections: true
    toc-depth: 1
    number-depth: 1
    theme: 
    - bcd-slides.scss